### ISSUE TITLE
Dashed link does not disappear when link selection dialog box is closed without selecting a link.

### ISSUE THREAD

**Issue by dovdori** [ObjectProcessMethodology/OPCloud-client#18] opened 2017-05-08 12:07 UTC
![image](https://cloud.githubusercontent.com/assets/5445726/25803370/2a154622-33ff-11e7-985b-ac53ebbd1c29.png)
 @TaerMosa 
@NataliLevi 
@ahmadjbara

**Comment by NataliLevi** [comment] 2017-05-08 12:10
Hi,
It is not a bug. All the link issues are in the project of Hilel. Starting
at the point of choosing a link to drawing it.
In a xase of closing the dialog without choosing a link, I don't think it
should disappear - the user has the option to choose the type later on the
inspector.

בתאריך 8 במאי 2017 15:07,‏ "dovdori" <notifications@github.com> כתב:

[image: image]
<https://cloud.githubusercontent.com/assets/5445726/25803370/2a154622-33ff-11e7-985b-ac53ebbd1c29.png>
@TaerMosa <https://github.com/TaerMosa>
@NataliLevi <https://github.com/NataliLevi>
@ahmadjbara <https://github.com/ahmadjbara>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ObjectProcessMethodology/OPCloud-client/issues/18>, or mute
the thread

**Closed** 2017-07-04 19:12 UTC
